### ISSUE TITLE
Update for Server 1.8.1

### ISSUE THREAD

**Issue by webframp** [gregf/chef-minecraft#38]

**Comment by sheldonh** [comment]
@fbrier Check out the https://github.com/webframp/cookbook-minecraft fork; it looks like @webframp proceeded with a fork instead of taking over as collaborator here, which @gregf's last comment might have led you to believe had happened.

**Comment by gregf** [comment]
I didn't know about this either, I'll update the readme to let people know.

**Comment by webframp** [comment]
It's a fork (since of course that's how github works) but I don't plan on maintaining it in isolation or as a replacement, the work I have there just wasn't ready for a PR. 

Whatever makes sense for those using it though I'm happy to do, if it's better to have it there we can just move the repo.

**Comment by gregf** [comment]
@webframp Doesn't really matter to me, I can transfer ownership of the repository if you want?

**Comment by webframp** [comment]
@gregf for now I'm ok with it as is, at least until I can fixup and finish any outstanding work in my fork. I'll have to delete my fork before you can transfer anyway

**Comment by webframp** [comment]
This issue is fixed with v0.5.2, now released
