### ISSUE TITLE
re-adding spigot support?

### ISSUE THREAD

**Issue by elijah** [gregf/chef-minecraft#43]
If I put together the proper chef resources to do the spigot / buildtools run from spigotmc - can we put the recently-removed bukkit/spigot bits back in?

My kid wants me to install the crazy craft modpack, i'm resistant to doing any of this without putting together better automation to make it easy to re-build when it eventually gets all torn up ;-)

best,
--e

**Comment by webframp** [comment]
Sounds reasonable to me if you can help maintain it. I don't use those myself, so don't have experience with them

**Comment by elijah** [comment]
I did most of this work yesterday and the day before - putting spigot and bukkit stuff back together, as part of making my kid happy :)  

I'll probably send a pull request soon, after I finish making sure that what i've done is not too much of an abomination.

As a reminder to myself - it would be useful to also provide sponge (vanilla, forge, sponge-api) support, and automate some of the upgrade processes (from other things to sponge) that are documented here:

https://docs.spongepowered.org/en/server/getting-started/migrating.html

I was fiddling with the minecraft_plugin LWRP yesterday - that's quite handy.  Enhancement possibility - there are some very common mods out there that are bundled as .zip files instead of jars - another lwrp there could be useful.

Also, there are a TON of things out there that are hidden behind redirects or ghetto PHP CDN links - a resource that is able to use curl smartly and pull from a URL and save to a specific filename would be good as well.  [e.g. - https://www.spigotmc.org/resources/ultra-cosmetics-2-opensource-and-free.10905/download?version=65455 , which winds up with a file named 'download\?version=65455' rather than something more useful...]

**Comment by elijah** [comment]
I am silly.  I should just wrap the remote_file resource for the crummy download links.  ;-)

--e

**Comment by webframp** [comment]
I'm not opposed to adding it back in if it's got test coverage and someone to help maintain it. Look forward to seeing the PR.

**Comment by gregf** [comment]
@elijah I have no interesting in adding this back in, but if you send a pull request I would be willing to add the tests myself if that is an issue.

Going to close this for now, but feel free to reopen once you have a pull request.
